### ISSUE TITLE
Crash on new zeroconf transaction detection

### ISSUE THREAD

**Issue by xavierfiechter** [Bitcoin-Brainbow/Brainbow#13]
```
[INFO   ] Awaiting queue..
[INFO   ] {'balance': {'confirmed': Decimal('0.00130587'), 'zeroconf': Decimal('0')}, 'txns': [<History: TXID:090c8295fdadd1f787b55fb0fc8ba0dfdc6424288484ae687cdf639347051c76 is_spend:True value:0.00062218 height:2346232 timestamp:2022-09-12 02:08:28>, <History: TXID:1095b2a75dad06838c65597ef93b7c5e6f5850836888e1ff80efa762425d8bb5 is_spend:True value:11.94709861 height:2346262 timestamp:2022-09-12 08:52:02>]}
[INFO   ] {'balance': {'confirmed': Decimal('0.00080169'), 'zeroconf': Decimal('0')}, 'txns': [<History: TXID:84616392a76ac589a36a3cf6178ec8ba96193f541911f3e81beb3cee8f94d9fa is_spend:True value:0.00080169 height:2346316 timestamp:2022-09-12 20:23:46>]}
[INFO   ] {'balance': {'confirmed': Decimal('0'), 'zeroconf': Decimal('0.0006632')}, 'txns': [<History: TXID:353ba067eccf63b7f75a3d9b224e110092f238292e0a1924e7da1b886614df54 is_spend:True value:0.0006632 height:0 timestamp:1663107168>]}
 Task exception was never retrieved
 future: <Task finished name='Task-2' coro=<NowalletApp.do_login() done, defined at ~/GitHub/Bitcoin-Brainbow/Brainbow/main.py:354> exception=TypeError("'<' not supported between instances of 'int' and 'datetime.datetime'")>
 Traceback (most recent call last):
   File "~/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 377, in do_login
     await asyncio.gather(
   File "~/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 441, in new_history_loop
     self.check_new_history()
   File "~/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 344, in check_new_history
     self.update_screens()
   File "~/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 432, in update_screens
     self.update_balance_screen()
   File "~/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 468, in update_balance_screen
     for hist in self.wallet.get_tx_history():
   File "~/GitHub/Bitcoin-Brainbow/Brainbow/nowallet/nowallet.py", line 444, in get_tx_history
     history.sort(reverse=True, key=lambda h: h.timestamp)
 TypeError: '<' not supported between instances of 'int' and 'datetime.datetime'
```

**Comment by xavierfiechter** [comment]
[INFO   ] Finished 'doing login tasks'
[INFO   ] all known addreses ['tb1pqq22ayfyqjgazz7sa3n4r6ge5ncw8gwvhkwqjd7p62', 'tb1pqq2x5jv8dm8fmmh7fj9m8larc9ruuxzmpfts7ndzah', 'tb1pqq2rfj6uqrr5wrpvap6dryma88vqst4a7mqqkk9k0n', 'tb1pqq2qr4u9sxc3hyu8pn0xy9qtfx54nc2pwzuqvh6hu2', 'tb1pqq22vk6cuxkf8j4vky932p5zakxxyjfn0jsstznagn', 'tb1pqq22l4c9ed30ym22mu0lwvu7f00gnnhre6hs9u46mz', 'tb1pqq2tngpkl0yss0kdchxsurddq3e6k6fxdqwq7fuf78', 'tb1pqq2xwg2qkefs5pupzvqf9qdtev3f68cqp5kqd2vvwf', 'tb1pqq2xy5wece6kh6uf6e2pznkrpxleegtg79cqne0ze7', 'tb1pqq2fuhtwa8a4fqt06qtumu7cta5j2dn0jqjsce72yp', 'tb1pqq2dkgkgkvzkpaaazphwdhcyp9anxf72nmhqj48jhh', 'tb1pqq286fgas5wpgary99ukxse2afc0m70fzppq7mpw0y', 'tb1pqq2tzcp448qfgnlnj2uslt4a3cdx3qjrlstqwg4v2y', 'tb1pqq2z6yhwsm92phlmgzp5f8fssp2gn6upmvysvr8qts', 'tb1pqq2p6nwutq3p6mh40wue2a28mrk3986zl7gsd93qwe', 'tb1pqq20az7cnmuxqsm88u43qnw68mr2q9drnglqmy8e46', 'tb1pqq2th54k66hngqkzkt2nvh6vpj7vzd8x7k4sqrvcph', 'tb1pqq2wtrwu7dvgyjtqj6hyhyrzwmsjwkh7lcjqyweqxu', 'tb1pqq2w0jzpmnqaawxk5rlfalh5l2uy2v7ntsesl0qcq8', 'tb1pqq2dta23huq4l6ev0v5tqdy2rhd5kj7hx6pq7ffw50', 'tb1pqq2qu8a9puaxfyerqruv376j5cu2ryg956gq4z8fyc', 'tb1pqq2vvrcsswl4c9h89c4xz4xdn4hn3ggzs8lq2edt0d', 'tb1pqq2pynxu7skpa0ds6xhwfz6suaemu8e80fjq6784k5', 'tb1pqq2vjrr8qavd2gazyt3n9akpasgnuf57f7lqsg9w08', 'tb1pqq2q3hskxa882lmufgdqqcd9vlhexyp08epq7h7shx', 'tb1pqq22dvnrnzn8eavl76mzv0tcre36tde2jjyqcxvdvl', 'tb1pqq2w0hr03pepryrv2fj4fjl4fgjwn55j74jq7msgee', 'tb1pqq2zj2etj4xm54avt8n2w0cn8ag2dmgxafcq82sqs0', 'tb1pqq2t3ughj45kyea0la22k2r5w0tdcrmqeahst4ammf', 'tb1pqq2ze0la5hnqhqs70ye98cgl8te7vd52eugs46lhhu', 'tb1pqq2p7cqyey72xv64ufmlsg4s8dnzke7sw23sxmeg63', 'tb1pqq2x8naq98jt68yz4tv96gmp7ppdah5hsdcsmq986s', 'tb1pqq2wk84f4hk0kwmc3rm58nr874vav7s6yl4sejexhr', 'tb1pqq2g0n4frrzaqrylzex48dlhw39gzz6umwys5rfwpc', 'tb1pqq20p8j2053g9q3t8glshvqkkuqftwka926qku89st', 'tb1pqq2rranjm38ullta8982tktmwqtlwevl49zs9ygvy5', 'tb1pqq2vlvrj88g9g8zaurtgz8f4mwaljckc6rqqfgcek4', 'tb1pqq2pw0zl9km3h5a3mv0vuh4e768vn3xxtqrqqq4gj0', 'tb1pqq2dl4mp6dc7ttggry487ewemwhxnksupglq2klkfs', 'tb1pqq2x0tc3nvpueyjd83y5n8ll9jul0lv0mwyswpzgkx']
[INFO   ] {'balance': {'confirmed': Decimal('0'), 'zeroconf': Decimal('0')}, 'txns': [<History: TXID:a739a5f97873bb8b1c8b7ad606879106ed50d63b8d411ec3c1e596986f579843 is_spend:True value:2 height:1488346 timestamp:2019-04-09 21:07:56>, <History: TXID:995d3606887ff1c3338129b3594b6bc8e4f7afd5758ad5b1b12c1ac8bed0ede5 is_spend:True value:0.15365698 height:1489455 timestamp:2019-04-17 09:49:32>, <History: TXID:5594e28f2472ba744b9b4ef194bef02828adf302cf10ee156936e090fe12710b is_spend:True value:3.7153435 height:2193305 timestamp:2022-04-05 20:16:29>]}
[INFO   ] {'balance': {'confirmed': Decimal('0'), 'zeroconf': Decimal('0')}, 'txns': [<History: TXID:0326252fc4e1aa340fa25a66650d200e37f6a07bc1c083fe5a89b581a5d6c937 is_spend:True value:0.5 height:1488346 timestamp:2019-04-09 21:07:56>, <History: TXID:5594e28f2472ba744b9b4ef194bef02828adf302cf10ee156936e090fe12710b is_spend:True value:3.7153435 height:2193305 timestamp:2022-04-05 20:16:29>]}
[INFO   ] {'balance': {'confirmed': Decimal('0'), 'zeroconf': Decimal('0.00055674')}, 'txns': [<History: TXID:357b2ec0418ae8a4a7bc3abd1dcbf0ab20e699caea8da92547c7e19b277e4bcb is_spend:True value:0.00055674 height:0 timestamp:1663138014>]}
 Task exception was never retrieved
 future: <Task finished name='Task-2' coro=<NowalletApp.do_login() done, defined at /GitHub/Bitcoin-Brainbow/Brainbow/main.py:354> exception=TypeError("'<' not supported between instances of 'int' and 'datetime.datetime'")>
 Traceback (most recent call last):
   File "/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 375, in do_login
     self.update_screens()
   File "/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 430, in update_screens
     self.update_balance_screen()
   File "/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 466, in update_balance_screen
     for hist in self.wallet.get_tx_history():
   File "/GitHub/Bitcoin-Brainbow/Brainbow/nowallet/nowallet.py", line 444, in get_tx_history
     history.sort(reverse=True, key=lambda h: h.timestamp)
 TypeError: '<' not supported between instances of 'int' and 'datetime.datetime'
[INFO   ] [Window      ] exiting mainloop and closing.

**Comment by xavierfiechter** [comment]
#FIXME:
# https://github.com/Bitcoin-Brainbow/Brainbow/issues/13#issuecomment-1246377734
#history.sort(reverse=True, key=lambda h: h.timestamp)
import time
try:

    # FIXME: CHECKME
    #history.sort(reverse=True, key=lambda h: h.timestamp)
except Exception as ex:
    print(traceback.format_exc())
    print("EX496 {}".format(ex))
    pass
