### ISSUE TITLE
Harden exchange rate retrieval.

### ISSUE THREAD

**Issue by xavierfiechter** [Bitcoin-Brainbow/Brainbow#25]
Fallback, in case the API(s) aren't available while starting the app.

**Comment by xavierfiechter** [comment]
future: <Task finished name='Task-2' coro=<NowalletApp.do_login() done, defined at /Users/~/GitHub/Bitcoin-Brainbow/Brainbow/main.py:381> exception=KeyError('EUR')>
 Traceback (most recent call last):
   File "/Users/~/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 404, in do_login
     await asyncio.gather(
   File "/Users/~/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 483, in update_exchange_rates
     self.show_snackbar("Exchange rates updated. {}".format(self.get_rate()))
   File "/Users/~/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 613, in get_rate
     rate = self.exchange_rates[self.price_api][self.currency] \
 KeyError: 'EUR'

**Comment by xavierfiechter** [comment]
Keep last known state before pulling fresh data.
