### ISSUE TITLE
Sign tx w/o broadcasting it leads to "insufficient inputs for outputs" exception.

### ISSUE THREAD

**Issue by xavierfiechter** [Bitcoin-Brainbow/Brainbow#30]
```
[INFO   ] unsigned_tx Tx [fc970e9685e1bc76e0f2a994d79f9d607d6f2c3c58cc75f8fa835b4928731811]
 Task exception was never retrieved
 future: <Task finished name='Task-31' coro=<NowalletApp.send_button_handler() done, defined at /Users/~/GitHub/Bitcoin-Brainbow/Brainbow/main.py:339> exception=ValueError('insufficient inputs for outputs')>
 Traceback (most recent call last):
   File "/Users/~/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 358, in send_button_handler
     await self.do_spend(address, amount, fee_rate)
   File "/Users/~/GitHub/Bitcoin-Brainbow/Brainbow/main.py", line 336, in do_spend
     self.spend_tuple = await self.wallet.spend(
   File "/Users/~/GitHub/Bitcoin-Brainbow/Brainbow/nowallet/nowallet.py", line 1056, in spend
     self._signtx(tx, in_addrs, fee)
   File "/Users/~/GitHub/Bitcoin-Brainbow/Brainbow/nowallet/nowallet.py", line 985, in _signtx
     distribute_from_split_pool(unsigned_tx, fee)
   File "/Users/~/GitHub/Bitcoin-Brainbow/Brainbow/env/lib/python3.10/site-packages/pycoin/tx/tx_utils.py", line 137, in distribute_from_split_pool
     raise ValueError("insufficient inputs for outputs")
 ValueError: insufficient inputs for outputs
```

**Comment by xavierfiechter** [comment]
See #64
