### ISSUE TITLE
open_tx_preview_bottom_sheet

### ISSUE THREAD

**Issue by xavierfiechter** [Bitcoin-Brainbow/Brainbow#95]
~/GitHub/Bitcoin-Brainbow/Brainbow/src/main.py", line 905, in send_button_handler
     self.tx_btm_sheet = open_tx_preview_bottom_sheet(self.drawer_bg_color, tx)
 TypeError: open_tx_preview_bottom_sheet() missing 2 required positional arguments: 'history' and 'wallet'

**Comment by xavierfiechter** [comment]
- [ ] Fee info

**Comment by xavierfiechter** [comment]
Broadcasting does not work..

 Task exception was never retrieved
 future: <Task finished name='Task-17' coro=<BrainbowApp.do_broadcast() done, defined at ~/GitHub/Bitcoin-Brainbow/Brainbow/src/main.py:827> exception=AttributeError("'NoneType' object has no attribute 'electrumx_script_hash'")>
 Traceback (most recent call last):
   File "~/GitHub/Bitcoin-Brainbow/Brainbow/src/main.py", line 831, in do_broadcast
     txid, exception = await self.wallet.broadcast(tx.as_hex(), chg_out)  # type: str
   File "~/GitHub/Bitcoin-Brainbow/Brainbow/src/nowallet.py", line 1001, in broadcast
     scripthash = self.get_address(change_key)
   File "~/GitHub/Bitcoin-Brainbow/Brainbow/src/nowallet.py", line 223, in get_address
     return key.electrumx_script_hash(bech32=self.bech32)
 AttributeError: 'NoneType' object has no attribute 'electrumx_script_hash'
[INFO   ] Interpreting new history..
[INFO   ] [New history is for address] 2N3wfSNnS4fAR5Dus3BRfgAXqqDCJZwYu2s
[INFO   ] [New history is for change] True
